### ISSUE TITLE
Failed to create connection: Error: API request failed. Request failed

### ISSUE THREAD

**Issue by pizza-777** [broxus/everscale-standalone-client#5]
I have started to get the error. A few weeks ago it worked well.
![Screenshot from 2022-09-29 07-52-02](https://user-images.githubusercontent.com/26024499/192941891-e99cb17a-311b-4363-bbee-094355665b22.png)
https://pizza-777.github.io/EverFile/#/file/0:895dfaebfd2c8f66383129f90131452c3749edf33fbb43434e6d728c1704c42d

This is the code where the error occurred:
![Screenshot from 2022-09-29 07-54-45](https://user-images.githubusercontent.com/26024499/192942372-53518202-efc6-4eb4-93da-e81ffe9e0767.png)

https://github.com/pizza-777/EverFile/blob/main/src/api.ts#L145

**Comment by Rexagon** [comment]
Please replace `mainnet` preset with the custom endpoint, acquired through the http://dashboard.evercloud.dev

```typescript
    connection: {
      id: 1,
      group: 'mainnet',
      type: 'graphql',
      data: {
        endpoints: ['https://mainnet.evercloud.dev/your-project-id/graphql'],
        local: false,
      }
    },
```

**Comment by pizza-777** [comment]
Now works well. Thanks.
