### ISSUE TITLE
Everscale-Standalone-Client Fails with Vite in Production

### ISSUE THREAD

**Issue by Nilay27** [broxus/everscale-standalone-client#9]
I am having an issue with the everscale-standalone-client when bundling for production using Vite. The application works fine in the development environment (localhost) but fails when deployed in production.

This is how I am initiating the client:

```
const Provider = new ProviderRpcClient({
      forceUseFallback: true,
      fallback: () =>
        EverscaleStandaloneClient.create({
          connection: {
            id: 1002, // network id
            group: "dev",
            type: 'jrpc',
            data: {
              endpoint: "https://jrpc-devnet.venom.foundation/rpc",
            },
          },
          initInput: '../../node_modules/nekoton-wasm/nekoton_wasm_bg.wasm',
        }),
    });
```

The error that I get is:
<img width="656" alt="Screenshot 2023-06-11 at 11 52 02 PM" src="https://github.com/broxus/everscale-standalone-client/assets/20042508/0b7bec78-e343-4202-9218-114324ad2ef3">

Upon closer inspection of the source, I found that the function the `y` in `await y(l.initInput);`  is invoked after 
`await ensureNekotonLoaded(params.initInput);` is called in `create()`

<img width="566" alt="Screenshot 2023-06-11 at 11 55 01 PM" src="https://github.com/broxus/everscale-standalone-client/assets/20042508/bc281782-3695-45ed-bae1-2040fa962ddb">

`ensureNekotonLoaded` is defined as 
```
core_1.default.ensureNekotonLoaded = (initInput) => {
    if (!clientInitializationStarted) {
        clientInitializationStarted = true;
        (0, nekoton_wasm_1.default)(initInput).then(notifyClientInitialized.resolve).catch(notifyClientInitialized.reject);
    }
    return initializationPromise;
};
```
So essentially the exact function corresponding to `y` should be `nekoton_wasm_1.default` which is nothing but the default import from `nekoton-wasm` .

I have identified the issue as to why it is undefined, in the source file `index.ts` the import from nekoton is defined as follows:

[`import init, * as nt from 'nekoton-wasm';
`](https://github.com/broxus/everscale-standalone-client/blob/eb19c9ce2cf49bdf6601cef21daf67280d8df947/src/index.ts#LL1)

However, the default export inside nekoton-wasm.js is not `init` but `__wbg_init`:

![Screenshot 2023-06-12 at 12 05 38 AM](https://github.com/broxus/everscale-standalone-client/assets/20042508/240ff3c5-c9b8-44a8-aa1c-404dfbbed3cf)

My guess is, this is the reason why the final build is unable to find the method and initialise it. 

However, I am not sure why this works perfectly on locally. 

[Link](https://github.com/Nilay27/bio-venom-sdk) to GitHub repo which works perfectly locally. (Need to do npm install in the root folder as well as inside src/sdk and src/touch-id-app, then run npm run dev in touch-id-app to start the application)

**Comment by LukaszWatroba** [comment]
Same here @Nilay27. Have you found any solution?
